[package]
name = "dist-server"
version = "0.1.0"
edition = "2021"

[dependencies]
library = { path = "../lib" }
clap = { version = "3.1.6", features = ["derive"] }
rkyv = { version = "0.7.36", features = ["alloc", "validation"] }
quit = "1.1.4"
