[package]
name = "library"
version = "0.1.0"
edition = "2021"

[dependencies]
rkyv = { version = "0.7.36", features = ["alloc", "validation"] }
tar = "0.4.38"
zstd = "0.11.1"
bytecheck = "0.6.7"
# heim = { version = "0.0", default-features = false, features = ["host"] }
# heim = "0.0.11"
